web:
  image: nginx:1.9
  ports:
    - "10090:80"
  volumes:
    - ./public:/var/www/html/public
    - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: ./docker/php
  volumes:
#    - ./docker/php/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./:/var/www/html
